# Generated by Django 2.0.5 on 2018-06-03 11:25

from django.db import migrations, models
import django.db.models.deletion
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to=gallery.models.gallery_pictures_uuid, verbose_name='thumbnail')),
                ('size', models.IntegerField(verbose_name='size')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='gallery.Picture', verbose_name='picture')),
            ],
            options={
                'verbose_name': 'thumbnail',
                'verbose_name_plural': 'thumbnails',
            },
        ),
    ]
