# Generated by Django 2.0.6 on 2018-06-04 19:25

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='thumbnail',
            field=models.ImageField(upload_to=gallery.models.gallery_thumbs_uuid, verbose_name='thumbnail'),
        ),
    ]
