# Generated by Django 2.1.1 on 2018-09-05 19:49

from django.db import migrations, models
import django.db.models.deletion
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20180604_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.URLField(blank=True, help_text='link to original vector', null=True, verbose_name='source')),
                ('vector', models.ImageField(upload_to=gallery.models.gallery_pictures_uuid, verbose_name='vector')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gallery.Author', verbose_name='author')),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gallery.License', verbose_name='license')),
            ],
            options={
                'verbose_name': 'vector',
                'verbose_name_plural': 'vectors',
            },
        ),
    ]
