# Generated by Django 2.1.1 on 2018-09-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vector',
            name='vector',
            field=models.ImageField(upload_to='gallery/vectors/', verbose_name='vector'),
        ),
    ]
