# Generated by Django 2.2.3 on 2019-07-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20180905_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thumbnail',
            options={'ordering': ('-size',), 'verbose_name': 'thumbnail', 'verbose_name_plural': 'thumbnails'},
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='size',
            field=models.IntegerField(blank=True, null=True, verbose_name='size'),
        ),
        migrations.AlterUniqueTogether(
            name='thumbnail',
            unique_together={('picture', 'size')},
        ),
    ]
