# Generated by Django 2.2.3 on 2019-07-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20190731_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thumbnail',
            options={'verbose_name': 'thumbnail', 'verbose_name_plural': 'thumbnails'},
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='size',
            field=models.IntegerField(default=0, verbose_name='size'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='thumbnail',
            unique_together=set(),
        ),
    ]
