# Generated by Django 2.0 on 2017-12-30 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rollingstock', '0003_auto_20171230_1830'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='supports markdown', null=True, verbose_name='description')),
                ('purchased', models.DateField(blank=True, null=True, verbose_name='purchase date')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='price')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='company name')),
                ('website', models.URLField(blank=True, null=True, verbose_name='website')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_vehicles', to='gallery.Picture', verbose_name='picture')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invetory_vehicles', to='rollingstock.Vehicle', verbose_name='vehicle')),
            ],
            options={
                'verbose_name': 'vehicle',
                'verbose_name_plural': 'vehicles',
                'ordering': ('vehicle',),
            },
        ),
        migrations.AddField(
            model_name='article',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manufactured_articles', to='inventory.Company', verbose_name='manufacturer'),
        ),
        migrations.AddField(
            model_name='article',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Article', verbose_name='set'),
        ),
        migrations.AddField(
            model_name='article',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marketed_articles', to='inventory.Company', verbose_name='vendor'),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('manufacturer', 'number')},
        ),
    ]
