# Generated by Django 2.0 on 2017-12-30 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='supports markdown', null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'configuration',
                'verbose_name_plural': 'configurations',
                'ordering': ('article',),
            },
        ),
        migrations.RemoveField(
            model_name='article',
            name='parent',
        ),
        migrations.AlterField(
            model_name='article',
            name='number',
            field=models.CharField(max_length=255, verbose_name='article number'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configurations', to='inventory.Article', verbose_name='article'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configurations', to='gallery.Picture', verbose_name='picture'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='configurations', to='inventory.Vehicle', verbose_name='vehicle'),
        ),
    ]
