# Generated by Django 2.0 on 2017-12-30 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rollingstock', '0003_auto_20171230_1830'),
        ('gallery', '0001_initial'),
        ('inventory', '0002_auto_20171230_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_assemblies', to='rollingstock.Assembly', verbose_name='assembly')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assemblies', to='inventory.Configuration', verbose_name='configuration')),
                ('picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_assemblies', to='gallery.Picture', verbose_name='picture')),
            ],
            options={
                'verbose_name': 'assembly',
                'verbose_name_plural': 'assemblies',
                'ordering': ('assembly',),
            },
        ),
    ]
