# Generated by Django 2.0 on 2017-12-31 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_assembly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assembly',
            name='configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assemblies', to='inventory.Configuration', verbose_name='configuration'),
        ),
    ]
