# Generated by Django 2.0 on 2017-12-31 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20171231_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='inventory.Article', verbose_name='article'),
        ),
    ]
