# Generated by Django 2.0 on 2018-01-01 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20171231_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuration',
            options={'ordering': ('vehicle',), 'verbose_name': 'configuration', 'verbose_name_plural': 'configurations'},
        ),
    ]
