# Generated by Django 2.0.6 on 2018-06-04 20:54

from django.db import migrations
import taggit_selectize.managers


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_configuration_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='tags',
            field=taggit_selectize.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
