# Generated by Django 2.1 on 2018-09-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20180818_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.IntegerField(choices=[(0, 'gekauft'), (1, 'bestellt'), (2, 'verkauft'), (3, 'entsorgt'), (3, 'gewünscht')], default=0, verbose_name='article status'),
        ),
    ]
