# Generated by Django 2.0 on 2017-12-30 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='assembly name')),
                ('number', models.CharField(blank=True, max_length=255, null=True, verbose_name='assembly number')),
                ('picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.Picture', verbose_name='picture')),
            ],
            options={
                'verbose_name': 'Assembly',
                'verbose_name_plural': 'Assemblies',
                'ordering': ('name', 'number', 'type'),
            },
        ),
        migrations.CreateModel(
            name='AssemblyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='assembly type name')),
            ],
            options={
                'verbose_name': 'Assembly type',
                'verbose_name_plural': 'Assembly types',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='operator name')),
                ('abbrev', models.CharField(max_length=255, unique=True, verbose_name='abbreviated operator name')),
            ],
            options={
                'verbose_name': 'operator',
                'verbose_name_plural': 'operators',
                'ordering': ('abbrev', 'name'),
            },
        ),
        migrations.AddField(
            model_name='assembly',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rollingstock.AssemblyType', verbose_name='assembly type'),
        ),
    ]
