# Generated by Django 2.0 on 2017-12-30 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        ('rollingstock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=255, null=True, verbose_name='vehicle number')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleKlass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klass', models.CharField(max_length=255, unique=True, verbose_name='class')),
                ('description', models.TextField(blank=True, help_text='supports markdown', verbose_name='description')),
            ],
            options={
                'verbose_name': 'vehicle class',
                'verbose_name_plural': 'vehicle classes',
                'ordering': ('klass',),
            },
        ),
        migrations.AlterField(
            model_name='assembly',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assemblies', to='gallery.Picture', verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assemblies', to='rollingstock.AssemblyType', verbose_name='assembly type'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='klass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='rollingstock.VehicleKlass', verbose_name='vehicle class'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='rollingstock.Operator', verbose_name='operator'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='gallery.Picture', verbose_name='picutre'),
        ),
    ]
