# Generated by Django 2.0 on 2017-12-30 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rollingstock', '0002_auto_20171230_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ('operator', 'klass', 'number'), 'verbose_name': 'vehicle', 'verbose_name_plural': 'vehicles'},
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='description',
            field=models.TextField(blank=True, help_text='supports markdown', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='gallery.Picture', verbose_name='picture'),
        ),
    ]
