# Generated by Django 2.0 on 2017-12-31 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rollingstock', '0003_auto_20171230_1830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ('klass', 'number'), 'verbose_name': 'vehicle', 'verbose_name_plural': 'vehicles'},
        ),
        migrations.AlterModelOptions(
            name='vehicleklass',
            options={'ordering': ('operator', 'klass'), 'verbose_name': 'vehicle class', 'verbose_name_plural': 'vehicle classes'},
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='operator',
        ),
        migrations.AddField(
            model_name='vehicleklass',
            name='operator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_klasses', to='rollingstock.Operator', verbose_name='operator'),
            preserve_default=False,
        ),
    ]
