# Generated by Django 2.0 on 2018-01-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rollingstock', '0004_auto_20171231_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleklass',
            name='revision',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='revision'),
        ),
        migrations.AddField(
            model_name='vehicleklass',
            name='revision_hidden',
            field=models.BooleanField(default=False, verbose_name='hide revision'),
        ),
    ]
