# Generated by Django 2.0 on 2018-01-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rollingstock', '0005_auto_20180101_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleklass',
            name='revision_hidden',
            field=models.BooleanField(default=False, help_text='for classes that have a revision that is not printed on the vehicle', verbose_name='hide revision'),
        ),
    ]
