# Generated by Django 2.0.5 on 2018-05-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rollingstock', '0006_auto_20180101_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleklass',
            name='klass',
            field=models.CharField(max_length=255, verbose_name='class'),
        ),
        migrations.AlterField(
            model_name='vehicleklass',
            name='revision_hidden',
            field=models.BooleanField(default=False, help_text='for classes that have a revision that is not displayed on the vehicle', verbose_name='hide revision'),
        ),
        migrations.AlterUniqueTogether(
            name='vehicleklass',
            unique_together={('klass', 'revision')},
        ),
    ]
