# Generated by Django 2.0.5 on 2018-05-06 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rollingstock', '0007_auto_20180506_0748'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together={('klass', 'number')},
        ),
    ]
