# Generated by Django 2.0.6 on 2018-06-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rollingstock', '0008_auto_20180506_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleklass',
            name='variant',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='variant'),
        ),
        migrations.AlterUniqueTogether(
            name='vehicleklass',
            unique_together={('klass', 'revision', 'variant')},
        ),
    ]
