# Generated by Django 2.1 on 2018-08-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rollingstock', '0009_auto_20180607_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleklass',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='slug'),
        ),
    ]
