# Generated by Django 2.1.1 on 2018-09-05 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20180905_2007'),
        ('rollingstock', '0010_vehicleklass_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='coat_of_armes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='gallery.Vector', verbose_name='coat of arms'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
    ]
