# Generated by Django 2.1.1 on 2018-09-05 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rollingstock', '0011_auto_20180905_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='coat_of_armes',
            new_name='coat_of_arms',
        ),
    ]
